spring:
  application.name: bienestar
  main.banner-mode: off
  datasource.url: jdbc:mariadb://localhost:3306/bienestar?user=root&password=pwd
  data.rest.base-path: /api

springdoc:
  open-api:
    info:
      title: "Bienestar API"
      version: "v1"
      description: "API para la aplicación Bienestar"
    security:
      - bearerAuth: [ ]
    components:
      security-schemes:
        bearerAuth:
          scheme: bearer

logging:
  level:
    "[org.springframework.data.rest]": DEBUG
    "[org.springframework.web]": DEBUG

    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": TRACE
    "[org.hibernate.orm.jdbc.extract]": TRACE
